[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build completed successfully'"
]

[start]
cmd = "python start.py"

[variables]
AUDIO_ANALYSIS_MODE = "simplified"
ENABLE_FULL_AUDIO_ANALYSIS = "false"
PYTHONPATH = "/app/backend" 