[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build completed successfully'"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[variables]
AUDIO_ANALYSIS_MODE = "simplified"
ENABLE_FULL_AUDIO_ANALYSIS = "false"
PYTHONPATH = "/app" 