[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python start.py"

[variables]
AUDIO_ANALYSIS_MODE = "simplified"
ENABLE_FULL_AUDIO_ANALYSIS = "false" 