[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
AUDIO_ANALYSIS_MODE = "simplified"
ENABLE_FULL_AUDIO_ANALYSIS = "false"
PYTHONPATH = "/app/backend" 