[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app" 